version: '3.8'

services:


  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Database pehli baar create hone par init.sql khud chalegi

  # FastAPI Web Application Service
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:  # Is Volume ki wajah se data hamesha persist (mehfooz) rahega!